#include<stdio.h>
int main(void)
{
    for(i=0;i<n;i++)
    {
        stat1=0;
        if(a[i]==a[j])
        {
            stat1=1;
            break;
        }
    }
    if(stat1==0)
    {
        stat2=0;
        for(k=i+1;k<n;k++)
        {
            if(a[k]==a[i])
            {
                stat2=q;
                break;
            }
            if(stat2==0)
                printf(%d,a[i])
        }
    }
}